#!/bin/bash

##  This function (re)configures clusterctrl to be one of 3 things, a bridge controller, a NAT controller or a node
##  Will make a backup of /etcdhcpcd.conf and /etc/sysctl.conf and override with pregenerated defaults designed for clusterctrl
##  params:
##	$1 : the type this will be (re)configured as. either bridge, nat or node
##	$2 : a number between 1-252 : this sets the last part of the static IP address

## TODO
##	 - add directory flag so can configure files on usbboot systems instead of directly on this one
##	 - dry run switch?
##	 -


##  Handles all the shared setup for all reconf types
##  params:
##	$1 : a number between 1-253, this sets the last part of the static IP address
function clusterctrl-reconfig-shared-begin {
#	check if line exists
#	else
#	append
#	echo '#net.ipv4.ip_forward=1 # ClusterCTRL' >> $MNT/etc/sysctl.conf

	# Backup kernel cmdline.txt file
	rm -f /boot/cmdline.old
	cp -f /boot/cmdline.txt /boot/cmdline.old

	# Raspi config changes
	raspi-config nonint do_serial 0
	raspi-config nonint do_i2c 0

	# Remove config file entries and add them back in later if needed
	## remove:
	sed -i "s# console=ttyGS0##" /boot/cmdline.txt

	## remove:
	sed -i "s# init=.*##" /boot/cmdline.txt

	## remove: eth0 from denyinterfaces line
	sed -i "s/^\(denyinterfaces.*\) eth0\(.*\)/\1\2/" /etc/dhcpcd.conf

	## if config exists
	if [ -f /etc/default/clusterctrl ];then
		## remove type and ID
		sed -i '/TYPE=.*/d' /etc/default/clusterctrl
		sed -i '/ID=.*/d' /etc/default/clusterctrl
	else
		## put default config back
		cp -f "$TEMPLATESDIR/default-clusterctrl" /etc/default/clusterctrl
	fi

	## remove old clusterctrl interfaces
	rm -f /etc/network/interfaces.d/clusterctrl

	## set the static ip to provided index
	sed -i "s~^static ip_address=172.19.181.*/24 #Cluster.*~static ip_address=172.19.181.$1/24 #ClusterCTRL~" /etc/dhcpcd.conf
}


##  Handles all the shared setup for controller types (bridge/nat)
##  params:
##	$1 : the interface name to copy [nat|bridge]
function clusterctrl-reconfig-controller-shared {

	## copy in the correct onces for the controller type
	cp -f "$TEMPLATEDIR/interfaces.$1" /etc/network/interfaces.d/clusterctrl

	# disable peripheral mode
	sed -i "s/^dtoverlay=dwc2.*$/#dtoverlay=dwc2,dr_mode=peripheral/" /boot/config.txt

	systemctl enable clusterctrl-init
	systemctl disable clusterctrl-composite
}

case $1 in
	Bridge | bridge | BRIDGE)
		clusterctrl-reconfig-shared-begin 253
		clusterctrl-reconfig-controller-shared bridge

		##fill in node addresses in etc/hosts

		sed -i 's#^\(denyinterfaces.*\)#\1 eth0#' /etc/dhcpcd.conf		
		sed -i "s/^net.ipv4.ip_forward=1 # ClusterCTRL/#net.ipv4.ip_forward=1 # ClusterCTRL/" /etc/sysctl.conf

		## set the TYPE in clusterctrl config to Bridge
		echo "TYPE=Bridge" >> /etc/default/clusterctrls

		echo "Recommend restart"
		;;
	Nat | nat | NAT )
		clusterctrl-reconfig-shared-begin 253
		clusterctrl-reconfig-controller-shared nat

		sed -i "s/^#net.ipv4.ip_forward=1 # Cluster.*/net.ipv4.ip_forward=1 # ClusterCTRL/" /etc/sysctl.conf

		##fill in node addresses in etc/hosts


		## set the TYPE in clusterctrl config to NAT
		echo "TYPE=NAT" >> /etc/default/clusterctrl

		echo "Recommend restart"

		;;
	Node | node | NODE)

		##validate $2 as index

		if [ $2 -gt 0 ] && [$2 -lt 253 ] ; then

			clusterctrl-reconfig-shared-begin $2

			## enable peripheral mode
			sed -i "s/^#dtoverlay=dwc2.*$/dtoverlay=dwc2,dr_mode=peripheral/" /boot/config.txt

			## set the TYPE in clusterctrl config to Node, and ID to index
			echo "TYPE=Node" >> /etc/default/clusterctrl
			echo "ID=" $2 >> /etc/default/clusterctrl

			## Re add eth0 to denied interfaces
			sed -i 's#^\(denyinterfaces.*\)#\1 eth0#' /etc/dhcpcd.conf

			##disable ipv4 forwarding
			sed -i "s/^net.ipv4.ip_forward=1 # ClusterCTRL/#net.ipv4.ip_forward=1 # ClusterCTRL/" /etc/sysctl.conf


			systemctl disable clusterctrl-init
			systemctl enable clusterctrl-composite

			echo "Recommend restart"

		else
			echo "Index out of bounds for node, cannot reconfigure"
		fi
		;;
	help | "--help" | "-h" | "")
		echo "Reconfigures this devices to be either a bridged controller, a NAT controller or a node"
		echo "	Usage: clusterctrl-reconfigure {bridge|nat|node} [1-252]"
		;;
	*)
		echo "unknown input, cannot reconfigure"
		;;
esac



