#!/bin/sh

##conf script
CONFIGFILE=/etc/default/clusterctrl
set -e
. /usr/share/debconf/confmodule


#	db_reset clusterctrl/device_type

# Load config file, if it exists.
if [ -e $CONFIGFILE ]; then
	. $CONFIGFILE || true
	# Store values from config file into
	# debconf db.
	db_set clusterctrl/device_type "$TYPE"
#else
	#	db_set clusterctrl/device_type "Bridge"
fi

# Ask questions.
db_input high clusterctrl/device_type || true
db_go || true
		
