#!/bin/sh

set -e
. /etc/default/clusterctrl
case "$1" in
    purge)
        if [ -e /usr/share/debconf/confmodule ]; then
                # Source debconf library and purge db
                . /usr/share/debconf/confmodule
                db_purge
        fi
	rm -r "$DATA_DIR"

	;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	rm -r "$DATA_DIR"
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
